#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#8762
server:
  port: 5089 
spring:
  application:
    name: service-srsj-console
#logbackConfigLocation: classpath:logback.xml
logging.config: classpath:logback.xml
#Socket policy
policy:
  host:0.0.0.0
  port:843
#minalog
mina:
  logfilter.enable: false   
keyframe: 
  cache.entry.max: 500
war: 
  deploy.server.check.interval: 600000
fileconsumer: 
  delayed.write: true
  queue.size: 120
  wait.for.keyframe: true
subscriberstream: 
  buffer.check.interval: 5000
  underrun.trigger: 100
  max.pending.frames: 10
  max.sequential.frames: 10
  auto.record: false
notify:
  systimer:
    tick: 50
filecache_maxsize: 500
filecache_purge: 10
#cache interal (in sec)
cache_interval: 10
multicast:
  executor_threads: 10
unicast:
  executor_threads: 4